<?php

/**
 * @author Ahmed Mohamed Ibrahim
 *
 * For the full copyright and license information, please view the LICENSE
 */

/**
 * Bubble Cache interface.
 *
 * Interface for caching and loading Bubble_Template classes
 * generated by the Bubble_Compiler.
 */
interface Bubble_Cache
{
    /**
     * Load a compiled Bubble_Template class from cache.
     *
     * @param string $key
     *
     * @return bool indicates successfully class load
     */
    public function load($key);

    /**
     * Cache and load a compiled Bubble_Template class.
     *
     * @param string $key
     * @param string $value
     */
    public function cache($key, $value);
}
